version: "3"

vars:
  BASE_IMAGE: jaedle/build-images-base
  BASE_TAG: latest
  BACKUP_IMAGE: jaedle/build-images-backup
  BACKUP_TAG: latest
  CONCOURSE_DIND_IMAGE: jaedle/build-images-concourse-docker-in-docker
  CONCOURSE_DIND_TAG: latest
  GIT_SHA:
    sh: git rev-parse --short HEAD
  TESTING_TAG: testing-{{.GIT_SHA}}

tasks:
  ci:
    desc: Run CI validations
    cmds:
      - task: base:build
      - task: backup:build
      - task: concourse-docker-in-docker:build

  world:
    desc: Build and release all images
    cmds:
      - task: ci
      - task: base:release
      - task: backup:release
      - task: concourse-docker-in-docker:release

  base:build-testing:
    desc: Build base image with testing tag (testing-<git-sha>)
    dir: base
    cmds:
      - docker build -t {{.BASE_IMAGE}}:{{.TESTING_TAG}} .

  concourse-docker-in-docker:build-testing:
    desc: Build concourse docker-in-docker image with testing tag
    dir: concourse-docker-in-docker
    cmds:
      - docker build --build-arg BASE_IMAGE={{.BASE_IMAGE}} --build-arg BASE_TAG={{.TESTING_TAG}} -t {{.CONCOURSE_DIND_IMAGE}}:{{.TESTING_TAG}} .

  backup:build-testing:
    desc: Build backup image with testing tag
    dir: backup
    cmds:
      - docker build --build-arg BASE_IMAGE={{.BASE_IMAGE}} --build-arg BASE_TAG={{.TESTING_TAG}} -t {{.BACKUP_IMAGE}}:{{.TESTING_TAG}} .

  base:build:
    desc: Build base image
    dir: base
    cmds:
      - docker build -t {{.BASE_IMAGE}}:{{.BASE_TAG}} .

  base:release:
    desc: Build and push base image
    cmds:
      - task: base:build
      - docker push {{.BASE_IMAGE}}:{{.BASE_TAG}}

  backup:build:
    desc: Build backup image
    dir: backup
    cmds:
      - docker build --build-arg BASE_IMAGE={{.BASE_IMAGE}} --build-arg BASE_TAG={{.BASE_TAG}} -t {{.BACKUP_IMAGE}}:{{.BACKUP_TAG}} .

  backup:release:
    desc: Build and push backup image
    cmds:
      - task: backup:build
      - docker push {{.BACKUP_IMAGE}}:{{.BACKUP_TAG}}

  concourse-docker-in-docker:build:
    desc: Build concourse docker-in-docker image
    dir: concourse-docker-in-docker
    cmds:
      - docker build --build-arg BASE_IMAGE={{.BASE_IMAGE}} --build-arg BASE_TAG={{.BASE_TAG}} -t {{.CONCOURSE_DIND_IMAGE}}:{{.CONCOURSE_DIND_TAG}} .

  concourse-docker-in-docker:release:
    desc: Build and push concourse docker-in-docker image
    cmds:
      - task: concourse-docker-in-docker:build
      - docker push {{.CONCOURSE_DIND_IMAGE}}:{{.CONCOURSE_DIND_TAG}}
