version: '3'

silent: true

env:
  CONCOURSE_HOST: 'ci.home.jaedle.de'
  CONCOURSE_SCHEMA: 'https'
  CONCOURSE_TEAM: 'main'
  CONCOURSE_PIPELINE: 'build-images'

tasks:
  login-ci:
    desc: Login into ci team
    cmd: fly login --target "$CONCOURSE_TEAM@$CONCOURSE_HOST" --concourse-url="${CONCOURSE_SCHEMA}://${CONCOURSE_HOST}" --team-name "$CONCOURSE_TEAM"

  set-pipeline:
    desc: Set pipeline
    cmd: fly set-pipeline --target "$CONCOURSE_TEAM@$CONCOURSE_HOST" --pipeline "$CONCOURSE_PIPELINE" --config pipeline.yaml
